# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shagit}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Gajdos"]
  s.date = %q{2010-03-18}
  s.default_executable = %q{shagit}
  s.description = %q{A simple web application for local, private git repository management}
  s.email = %q{contact@roboprojects.com}
  s.executables = ["shagit"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "CHANGES",
     "LICENSE",
     "README.md",
     "VERSION.yml",
     "config.ru",
     "config.yml",
     "lib/authorization.rb",
     "lib/config_info.rb",
     "lib/enhancing_grit.rb",
     "lib/helpers/helpers.rb",
     "lib/shagit.rb",
     "public/buttons.css",
     "public/reset.css",
     "public/shagit.css",
     "rakefile",
     "shagit_app.rb",
     "test/acceptance/acceptance_test.rb",
     "test/unit/shagit_test.rb",
     "views/delete.haml",
     "views/delete_confirmation.haml",
     "views/index.haml",
     "views/layout.haml",
     "views/login.haml",
     "views/login_failed.haml",
     "views/logout.haml",
     "views/new.haml",
     "views/new_confirmation.haml",
     "views/repo.haml"
  ]
  s.homepage = %q{http://github.com/unabatede/shagit}
  s.post_install_message = %q{
  ========================================================================
  Thanks for installing Shagit!
  ------------------------------------------------------------------------
  Please set the path to your working directory within the config.yml file
  before starting Shagit.

  Once you're done, you can start Shagit by running the following command:
    shagit

  For a production environment you should consider using Phusion Passenger
  or any of the other known Ruby deployment solutions that can be run as a
  daemon. 

  Find out more and get involved:
    http://github.com/unabatede/shagit
  ========================================================================
  }
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A simple web application for local, private git repository management}
  s.test_files = [
    "test/acceptance/acceptance_test.rb",
     "test/unit/shagit_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.20"])
      s.add_runtime_dependency(%q<grit>, [">= 2.0.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<haml>, [">= 2.2.20"])
      s.add_dependency(%q<grit>, [">= 2.0.0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_dependency(%q<webrat>, [">= 0.7.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<haml>, [">= 2.2.20"])
    s.add_dependency(%q<grit>, [">= 2.0.0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.3"])
    s.add_dependency(%q<webrat>, [">= 0.7.0"])
  end
end

